services:
  app:
    container_name: app

    build:
      context: .
      dockerfile: ./containers/django/Dockerfile

    environment:    
      - DJANGO_SETTINGS_MODULE=app_config.settings
      - GOOGLE_APPLICATION_CREDENTIALS=/code/key.json 



    volumes:
      - .:/code
      - ~/.config:/root/.config:ro
      - ../key.json:/code/key.json

    ports:
      - 8000:8000

        
    env_file:
      - ../.env

    command: sh -c "/usr/local/bin/entrypoint.sh" 