services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./containers/django/Dockerfile
    environment:    
      - DJANGO_SETTINGS_MODULE=app_config.settings
      - GOOGLE_APPLICATION_CREDENTIALS=/code/key.json
    volumes:
      - .:/code
      - ~/.config:/root/.config:ro
      - ../key.json:/code/key.json
      - /etc/letsencrypt/:/etc/letsencrypt:ro
    expose:
      - "8000"
    env_file:
      - ../.env
    command: sh -c "/usr/local/bin/entrypoint.sh"

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    volumes:
      - ./static:/static
    ports:
      - "80:80"
      - "443:443" 
    depends_on:
      - app
