# Generated by Django 5.1.3 on 2024-12-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
