# Generated by Django 5.1.3 on 2024-12-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0002_alter_customgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
