# Generated by Django 2.1.5 on 2025-01-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0002_alter_customgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
