# Generated by Django 4.2.13 on 2025-01-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0003_auto_20250102_1341'),
        ('app_folder', '0003_purchase_group'),
    ]

    operations = [
    ]
