# Generated by Django 5.1.3 on 2024-12-17 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0003_customgroup_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='store_name',
        ),
        migrations.AddField(
            model_name='customgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customgroup',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
