# Generated by Django 4.2.13 on 2025-01-08 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0006_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='group_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='app_folder.customgroup'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['group', 'date'], name='app_folder__group_i_c3b90b_idx'),
        ),
    ]
