# Generated by Django 4.2.13 on 2025-01-09 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0007_remove_purchase_group_id_purchase_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
