# Generated by Django 4.2.13 on 2025-01-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0008_customgroup_invite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='invite_token',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
